services:
  - type: web
    name: dial-a-drink-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://dial-a-drink-backend.onrender.com/api
