# Cloud Build configuration for Development Backend
# This file deploys to deliveryos-development-backend from develop branch

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/deliveryos-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/deliveryos-backend:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/deliveryos-backend:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/deliveryos-backend:latest'

  # Deploy to development backend service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'deliveryos-development-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/deliveryos-backend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--timeout'
      - '300'
      - '--add-cloudsql-instances'
      - 'dialadrink-production:us-central1:dialadrink-db-dev'
      - '--update-env-vars'
      - 'NODE_ENV=development,FRONTEND_URL=https://dialadrink.thewolfgang.tech,ADMIN_URL=https://dialadrink-admin.thewolfgang.tech,HOST=0.0.0.0'
      # Note: DATABASE_URL should be set manually or via Secret Manager

images:
  - 'gcr.io/$PROJECT_ID/deliveryos-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/deliveryos-backend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
