services:
  - type: web
    name: dial-a-drink-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: dial-a-drink-db
          property: connectionString

