# Cloud Build configuration for Admin Frontend - Development
# This file enables automatic deployments from GitHub develop branch to Cloud Run

steps:
  # Build the container image with development backend URL
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/deliveryos-admin-dev:${BUILD_ID}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/deliveryos-admin-dev:latest'
      - '--build-arg'
      - 'REACT_APP_API_URL=https://deliveryos-development-backend-lssctajjoq-uc.a.run.app/api'
      - '--build-arg'
      - 'REACT_APP_GOOGLE_MAPS_API_KEY=${_GOOGLE_MAPS_API_KEY}'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/deliveryos-admin-dev:${BUILD_ID}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/deliveryos-admin-dev:latest'

  # Deploy container image to Cloud Run (development)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'deliveryos-admin-frontend-dev'
      - '--image'
      - 'gcr.io/$PROJECT_ID/deliveryos-admin-dev:${BUILD_ID}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '256Mi'
      - '--set-env-vars'
      - 'REACT_APP_API_URL=https://deliveryos-development-backend-lssctajjoq-uc.a.run.app/api,REACT_APP_GOOGLE_MAPS_API_KEY=${_GOOGLE_MAPS_API_KEY}'

images:
  - 'gcr.io/$PROJECT_ID/deliveryos-admin-dev:${BUILD_ID}'
  - 'gcr.io/$PROJECT_ID/deliveryos-admin-dev:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

# Substitution variables - must be set via Cloud Build trigger or --substitutions flag
substitutions:
  _GOOGLE_MAPS_API_KEY: ''  # REQUIRED: Set this in Cloud Build trigger configuration
